/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
module.exports = {
	sidebar: [
		{
			id: 'welcome',
			type: 'doc',
			label: 'Welcome'
		},
		{
			type: 'category',
			label: 'Guides',
			collapsed: true,
			items: [
				{
					type: 'autogenerated',
					dirName: 'guides'
				}
			]
		},
		{
			type: 'category',
			label: 'Documentation',
			collapsed: true,
			items: [
				{
					type: 'autogenerated',
					dirName: 'documentation'
				}
			]
		}
	]
};
